app_name = "gin study"
# 所有的key需小写
# possible values: DEBUG, INFO, WARNING, ERROR, FATAL
log_level = "DEBUG"
[web]
address = "127.0.0.1:3000"
certpath = "D:/make-money/go-mod/src/private.pem" #私钥证书
[mysql]
dnsapp = "root:root@tcp(127.0.0.1:3306)/ucg?charset=utf8mb4"
debug = true  #true为全局打印sql
maxidleconns = 10   #最大闲置连接数
maxopenconns = 100  #最大连接数
maxconnmaxlifetime = 3000 #设置链接可以重用时长

[redis]
ip = "127.0.0.1"
port = 6479